/*
 * Frozen-Bubble SDL2 C++ Port
 * Copyright (c) 2000-2012 The Frozen-Bubble Team
 * Copyright (c) 2026 Huy Chau
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "platform.h"
#include <SDL2/SDL.h>

std::string g_dataDir;

#ifdef __ANDROID__
#include <SDL2/SDL_rwops.h>
#include <sys/stat.h>

// List of all asset files to extract from APK to writable storage.
// Must be kept in sync with the share/ directory contents.
static const char* ASSET_FILES[] = {
    // Add all asset paths here relative to share/
    // e.g. "gfx/menu/back_start.png"
    // This will be generated by a build script.
    nullptr
};

static void extractAssets(const std::string& destDir) {
    // This is a placeholder. On Android, assets are listed and extracted
    // from the APK via SDL_AndroidGetActivity() + AssetManager JNI calls.
    // For now, we rely on SDL2's built-in asset manager path resolution
    // by using relative paths with SDL_RWFromFile.
    (void)destDir;
    SDL_Log("Android: using APK asset manager for data files");
}

void InitDataDir() {
    // On Android, SDL_RWFromFile("gfx/foo.png", "rb") automatically
    // uses the Android Asset Manager for relative paths.
    // Set g_dataDir to empty so ASSET("/gfx/foo.png") becomes "/gfx/foo.png"
    // but we strip the leading slash for Android asset paths.
    g_dataDir = "";
}

#elif defined(__WASM_PORT__)

// WebAssembly uses Emscripten virtual filesystem
// Assets are preloaded via --preload-file share@/share
void InitDataDir() {
    g_dataDir = "/share";  // Virtual filesystem path
}

#else // Desktop platforms

void InitDataDir() {
    g_dataDir = DATA_DIR;
}

#endif
