/*
 * Frozen-Bubble SDL2 C++ Port
 * Copyright (c) 2000-2012 The Frozen-Bubble Team
 * Copyright (c) 2026 Huy Chau
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "platform.h"
#include <SDL2/SDL.h>

std::string g_dataDir;

#ifdef __ANDROID__
#include <SDL2/SDL_rwops.h>
#include <sys/stat.h>

// List of all asset files to extract from APK to writable storage.
// Must be kept in sync with the share/ directory contents.
static const char* ASSET_FILES[] = {
    // Add all asset paths here relative to share/
    // e.g. "gfx/menu/back_start.png"
    // This will be generated by a build script.
    nullptr
};

static void extractAssets(const std::string& destDir) {
    // This is a placeholder. On Android, assets are listed and extracted
    // from the APK via SDL_AndroidGetActivity() + AssetManager JNI calls.
    // For now, we rely on SDL2's built-in asset manager path resolution
    // by using relative paths with SDL_RWFromFile.
    (void)destDir;
    SDL_Log("Android: using APK asset manager for data files");
}

void InitDataDir() {
    // Assets are extracted from the APK to internal storage by AssetExtractor.java
    // (called in FrozenBubbleActivity.onCreate before SDL starts).
    // SDL_AndroidGetInternalStoragePath() returns the same path as context.getFilesDir(),
    // e.g. /data/user/0/org.frozenbubble/files — we append /share to match extraction dest.
    const char* internalPath = SDL_AndroidGetInternalStoragePath();
    if (internalPath) {
        g_dataDir = std::string(internalPath) + "/share";
    } else {
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION,
                     "SDL_AndroidGetInternalStoragePath() returned null — using hardcoded fallback");
        g_dataDir = "/data/data/org.frozenbubble/files/share";
    }
    SDL_Log("Android data dir: %s", g_dataDir.c_str());
}

#elif defined(__WASM_PORT__)

// WebAssembly uses Emscripten virtual filesystem
// Assets are preloaded via --preload-file share@/share
void InitDataDir() {
    g_dataDir = "/share";  // Virtual filesystem path
}

#else // Desktop platforms

void InitDataDir() {
    g_dataDir = DATA_DIR;
}

#endif
